#
# Ref:
#   https://docs.travis-ci.com/user/languages/python/
#

language: python

before_install:
  - pip install coveralls
  - pip install -r requirements-dev.txt
  - pip install -r requirements_dev.txt

install:
  - pip install -r requirements.txt

script:
  - make test-detailed test-bash

after_success:
  - coveralls

