#
# Ref:
#   https://docs.travis-ci.com/user/languages/python/
#

language: python

install:
  - pip install -r requirements.txt

script:
  - make test-detailed test-bash

after_success:
  - coveralls

