#
# Ref:
#   https://docs.travis-ci.com/user/languages/python/
#

language: python

# coveralls:
#   - only used/installed on TravisCI
#
before_install:
  - pip install -r requirements_dev.txt
  - pip install -r requirements.txt
# - pipenv sync

install:
  - pip install -e .

script:
  - make test-detailed test-bash

after_success:
  - coveralls

